namespace FlowerShop.Clientes
{
    partial class frmClientes
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlTop = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.btnAñadirCliente = new System.Windows.Forms.Button();
            this.pnlPaddingCentral = new System.Windows.Forms.Panel();
            this.pnlContenedorPrincipal = new System.Windows.Forms.Panel();
            this.pnlSidebarDerecho = new System.Windows.Forms.Panel();
            this.pnlListaClientes = new System.Windows.Forms.Panel();
            this.dgvClientes = new System.Windows.Forms.DataGridView();
            this.pnlBuscador = new System.Windows.Forms.Panel();
            this.label8 = new System.Windows.Forms.Label();
            this.textBox7 = new System.Windows.Forms.TextBox();
            this.pnlDatosP = new System.Windows.Forms.Panel();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.txtNombre = new System.Windows.Forms.TextBox();
            this.lblApPaterno = new System.Windows.Forms.Label();
            this.txtApPaterno = new System.Windows.Forms.TextBox();
            this.lblApMaterno = new System.Windows.Forms.Label();
            this.txtApMaterno = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtTelefono = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtRedSocial = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.textBox6 = new System.Windows.Forms.TextBox();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.pnlTop.SuspendLayout();
            this.pnlPaddingCentral.SuspendLayout();
            this.pnlContenedorPrincipal.SuspendLayout();
            this.pnlListaClientes.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvClientes)).BeginInit();
            this.pnlBuscador.SuspendLayout();
            this.pnlDatosP.SuspendLayout();
            this.SuspendLayout();
            this.pnlTop.Controls.Add(this.lblTitulo);
            this.pnlTop.Controls.Add(this.btnAñadirCliente);
            this.pnlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlTop.Location = new System.Drawing.Point(0, 0);
            this.pnlTop.Name = "pnlTop";
            this.pnlTop.Size = new System.Drawing.Size(1200, 100);
            this.pnlTop.TabIndex = 0;
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(33)))), ((int)(((byte)(61)))));
            this.lblTitulo.Location = new System.Drawing.Point(35, 25);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(171, 46);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "CLIENTES";
            this.btnAñadirCliente.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAñadirCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(163)))), ((int)(((byte)(17)))));
            this.btnAñadirCliente.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAñadirCliente.FlatAppearance.BorderSize = 0;
            this.btnAñadirCliente.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAñadirCliente.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnAñadirCliente.ForeColor = System.Drawing.Color.White;
            this.btnAñadirCliente.Location = new System.Drawing.Point(980, 25);
            this.btnAñadirCliente.Name = "btnAñadirCliente";
            this.btnAñadirCliente.Size = new System.Drawing.Size(180, 40);
            this.btnAñadirCliente.TabIndex = 1;
            this.btnAñadirCliente.Text = "+ Nuevo Cliente";
            this.btnAñadirCliente.UseVisualStyleBackColor = false;
            this.btnAñadirCliente.Click += new System.EventHandler(this.btnAñadirCliente_Click_1);
            this.pnlPaddingCentral.Controls.Add(this.pnlContenedorPrincipal);
            this.pnlPaddingCentral.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlPaddingCentral.Location = new System.Drawing.Point(0, 100);
            this.pnlPaddingCentral.Name = "pnlPaddingCentral";
            this.pnlPaddingCentral.Padding = new System.Windows.Forms.Padding(45, 10, 45, 30);
            this.pnlPaddingCentral.Size = new System.Drawing.Size(1200, 600);
            this.pnlPaddingCentral.TabIndex = 1;
            this.pnlSidebarDerecho.BackColor = System.Drawing.Color.White;
            this.pnlSidebarDerecho.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlSidebarDerecho.Dock = System.Windows.Forms.DockStyle.Right;
            this.pnlSidebarDerecho.Location = new System.Drawing.Point(700, 0);
            this.pnlSidebarDerecho.Name = "pnlSidebarDerecho";
            this.pnlSidebarDerecho.Size = new System.Drawing.Size(500, 700);
            this.pnlSidebarDerecho.TabIndex = 6;
            this.pnlSidebarDerecho.AutoScroll = true;
            this.pnlSidebarDerecho.Visible = false;
            this.pnlContenedorPrincipal.BackColor = System.Drawing.Color.Transparent;
            this.pnlContenedorPrincipal.Controls.Add(this.pnlListaClientes);
            this.pnlContenedorPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContenedorPrincipal.Location = new System.Drawing.Point(45, 10);
            this.pnlContenedorPrincipal.Name = "pnlContenedorPrincipal";
            this.pnlContenedorPrincipal.Size = new System.Drawing.Size(1110, 560);
            this.pnlContenedorPrincipal.TabIndex = 0;
            this.pnlListaClientes.BackColor = System.Drawing.Color.White;
            this.pnlListaClientes.Controls.Add(this.dgvClientes);
            this.pnlListaClientes.Controls.Add(this.pnlBuscador);
            this.pnlListaClientes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlListaClientes.Location = new System.Drawing.Point(0, 0);
            this.pnlListaClientes.Name = "pnlListaClientes";
            this.pnlListaClientes.Padding = new System.Windows.Forms.Padding(15);
            this.pnlListaClientes.Size = new System.Drawing.Size(740, 560);
            this.pnlListaClientes.TabIndex = 0;
            this.dgvClientes.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvClientes.BackgroundColor = System.Drawing.Color.White;
            this.dgvClientes.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvClientes.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvClientes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvClientes.Location = new System.Drawing.Point(15, 75);
            this.dgvClientes.Name = "dgvClientes";
            this.dgvClientes.ReadOnly = true;
            this.dgvClientes.AllowUserToAddRows = false;
            this.dgvClientes.AllowUserToDeleteRows = false;
            this.dgvClientes.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvClientes.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.LightGray;
            this.dgvClientes.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;

            this.dgvClientes.RowHeadersVisible = false;
            this.dgvClientes.RowHeadersWidth = 51;
            this.dgvClientes.RowTemplate.Height = 24;
            this.dgvClientes.Size = new System.Drawing.Size(710, 470);
            this.dgvClientes.TabIndex = 1;
            this.dgvClientes.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvClientes_CellClick);
            this.pnlBuscador.Controls.Add(this.label8);
            this.pnlBuscador.Controls.Add(this.textBox7);
            this.pnlBuscador.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlBuscador.Location = new System.Drawing.Point(15, 15);
            this.pnlBuscador.Name = "pnlBuscador";
            this.pnlBuscador.Size = new System.Drawing.Size(710, 60);
            this.pnlBuscador.TabIndex = 0;
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(33)))), ((int)(((byte)(61)))));
            this.label8.Location = new System.Drawing.Point(0, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(120, 23);
            this.label8.TabIndex = 0;
            this.label8.Text = "Buscar cliente";
            this.textBox7.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.textBox7.Location = new System.Drawing.Point(0, 25);
            this.textBox7.Name = "textBox7";
            this.textBox7.Size = new System.Drawing.Size(300, 30);
            this.textBox7.TabIndex = 1;
            this.textBox7.TextChanged += new System.EventHandler(this.textBox7_TextChanged);
            this.pnlDatosP.BackColor = System.Drawing.Color.White;
            this.pnlDatosP.Controls.Add(this.label2);
            this.pnlDatosP.Controls.Add(this.label3);
            this.pnlDatosP.Controls.Add(this.txtNombre);
            this.pnlDatosP.Controls.Add(this.lblApPaterno);
            this.pnlDatosP.Controls.Add(this.txtApPaterno);
            this.pnlDatosP.Controls.Add(this.lblApMaterno);
            this.pnlDatosP.Controls.Add(this.txtApMaterno);
            this.pnlDatosP.Controls.Add(this.label4);
            this.pnlDatosP.Controls.Add(this.txtTelefono);
            this.pnlDatosP.Controls.Add(this.label5);
            this.pnlDatosP.Controls.Add(this.txtRedSocial);
            this.pnlDatosP.Controls.Add(this.label6);
            this.pnlDatosP.Controls.Add(this.textBox6);
            this.pnlDatosP.Controls.Add(this.button2);
            this.pnlDatosP.Controls.Add(this.button3);
            this.pnlDatosP.Dock = System.Windows.Forms.DockStyle.Right;
            this.pnlDatosP.Location = new System.Drawing.Point(740, 0);
            this.pnlDatosP.Name = "pnlDatosP";
            this.pnlDatosP.Size = new System.Drawing.Size(370, 560);
            this.pnlDatosP.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(33)))), ((int)(((byte)(61)))));
            this.label2.Location = new System.Drawing.Point(20, 20);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(205, 32);
            this.label2.TabIndex = 0;
            this.label2.Text = "Datos del cliente";
            this.label2.Click += new System.EventHandler(this.label2_Click);
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label3.Location = new System.Drawing.Point(20, 70);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(73, 23);
            this.label3.TabIndex = 1;
            this.label3.Text = "Nombre";
            this.txtNombre.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtNombre.Location = new System.Drawing.Point(20, 95);
            this.txtNombre.Name = "txtNombre";
            this.txtNombre.Size = new System.Drawing.Size(317, 30);
            this.txtNombre.TabIndex = 2;
            this.txtNombre.TextChanged += new System.EventHandler(this.txtNombre_TextChanged);
            this.lblApPaterno.AutoSize = true;
            this.lblApPaterno.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblApPaterno.Location = new System.Drawing.Point(20, 130);
            this.lblApPaterno.Name = "lblApPaterno";
            this.lblApPaterno.Size = new System.Drawing.Size(136, 23);
            this.lblApPaterno.TabIndex = 3;
            this.lblApPaterno.Text = "Apellido Paterno";
            this.txtApPaterno.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtApPaterno.Location = new System.Drawing.Point(20, 155);
            this.txtApPaterno.Name = "txtApPaterno";
            this.txtApPaterno.Size = new System.Drawing.Size(317, 30);
            this.txtApPaterno.TabIndex = 4;
            this.lblApMaterno.AutoSize = true;
            this.lblApMaterno.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblApMaterno.Location = new System.Drawing.Point(20, 190);
            this.lblApMaterno.Name = "lblApMaterno";
            this.lblApMaterno.Size = new System.Drawing.Size(142, 23);
            this.lblApMaterno.TabIndex = 5;
            this.lblApMaterno.Text = "Apellido Materno";
            this.txtApMaterno.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtApMaterno.Location = new System.Drawing.Point(20, 215);
            this.txtApMaterno.Name = "txtApMaterno";
            this.txtApMaterno.Size = new System.Drawing.Size(317, 30);
            this.txtApMaterno.TabIndex = 6;
            this.txtApMaterno.TextChanged += new System.EventHandler(this.textBox1_TextChanged);
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label4.Location = new System.Drawing.Point(20, 250);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(74, 23);
            this.label4.TabIndex = 7;
            this.label4.Text = "TelÃ©fono";
            this.txtTelefono.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtTelefono.Location = new System.Drawing.Point(20, 275);
            this.txtTelefono.Name = "txtTelefono";
            this.txtTelefono.Size = new System.Drawing.Size(317, 30);
            this.txtTelefono.TabIndex = 8;
            this.txtTelefono.TextChanged += new System.EventHandler(this.textBox3_TextChanged);
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label5.Location = new System.Drawing.Point(20, 310);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(88, 23);
            this.label5.TabIndex = 9;
            this.label5.Text = "Red Social";
            this.txtRedSocial.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtRedSocial.Location = new System.Drawing.Point(20, 335);
            this.txtRedSocial.Name = "txtRedSocial";
            this.txtRedSocial.Size = new System.Drawing.Size(317, 30);
            this.txtRedSocial.TabIndex = 10;
            this.txtRedSocial.TextChanged += new System.EventHandler(this.textBox5_TextChanged);
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.label6.Location = new System.Drawing.Point(20, 370);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(81, 23);
            this.label6.TabIndex = 11;
            this.label6.Text = "DirecciÃ³n";
            this.textBox6.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.textBox6.Location = new System.Drawing.Point(20, 395);
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new System.Drawing.Size(317, 30);
            this.textBox6.TabIndex = 12;
            this.textBox6.TextChanged += new System.EventHandler(this.textBox6_TextChanged);
            this.button2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.button2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(163)))), ((int)(((byte)(17)))));
            this.button2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button2.FlatAppearance.BorderSize = 0;
            this.button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button2.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.button2.ForeColor = System.Drawing.Color.White;
            this.button2.Location = new System.Drawing.Point(175, 490);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(135, 30);
            this.button2.TabIndex = 13;
            this.button2.Text = "Guardar";
            this.button2.UseVisualStyleBackColor = false;
            this.button3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.button3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(49)))), ((int)(((byte)(49)))));
            this.button3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button3.FlatAppearance.BorderSize = 0;
            this.button3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button3.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.button3.ForeColor = System.Drawing.Color.White;
            this.button3.Location = new System.Drawing.Point(20, 490);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(135, 30);
            this.button3.TabIndex = 14;
            this.button3.Text = "Eliminar";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(245)))));
            this.ClientSize = new System.Drawing.Size(1200, 700);
            this.Controls.Add(this.pnlSidebarDerecho);
            this.Controls.Add(this.pnlPaddingCentral);
            this.Controls.Add(this.pnlTop);
            this.Name = "frmClientes";
            this.Text = "Clientes";
            this.Load += new System.EventHandler(this.frmClientes_Load);
            this.pnlTop.ResumeLayout(false);
            this.pnlTop.PerformLayout();
            this.pnlPaddingCentral.ResumeLayout(false);
            this.pnlContenedorPrincipal.ResumeLayout(false);
            this.pnlListaClientes.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvClientes)).EndInit();
            this.pnlBuscador.ResumeLayout(false);
            this.pnlBuscador.PerformLayout();
            this.pnlDatosP.ResumeLayout(false);
            this.pnlDatosP.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlTop;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Button btnAñadirCliente;
        private System.Windows.Forms.Panel pnlPaddingCentral;
        private System.Windows.Forms.Panel pnlSidebarDerecho;
        private System.Windows.Forms.Panel pnlContenedorPrincipal;
        private System.Windows.Forms.Panel pnlListaClientes;
        private System.Windows.Forms.Panel pnlBuscador;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.DataGridView dgvClientes;
        private System.Windows.Forms.Panel pnlDatosP;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox txtNombre;
        private System.Windows.Forms.Label lblApPaterno;
        private System.Windows.Forms.TextBox txtApPaterno;
        private System.Windows.Forms.Label lblApMaterno;
        private System.Windows.Forms.TextBox txtApMaterno;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtTelefono;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtRedSocial;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
    }
}





